name: "Deploy to AWS S3"
description: "deploy a static website via aws S3"
inputs:
  bucket:
    description: "the s3 bucketname."
    required: true
  bucket-region:
    description: "region of bucket."
    required: false
    default: "us-east-1"
  dist-folder:
    description: "The folder contains app artifacts"
    required: true
outputs:
  website-url:
    description: "url of our website"
runs:
  using: "node16"
  main: main.js
